title: Lerumo Molamohale
description: Portfolio â€” copywriting, content, prompt engineering
baseurl: "" # the subpath, leave empty for user site
url: "https://lerumolamohale.me"
theme: minima
plugins: []
